# Release task for PbLib projects
# See https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema for reference

pool:
  vmImage: windows-latest
  demands: Cmd

trigger:
  branches:
    include:
      - refs/tags/*
pr: none

variables:
  - group: nugetKeys #create this group with SECRET variables `nugetKey`
  - name: githubConnectionName
    value: AkkaDotNet_Releases #replace this
  - name: projectName
    value: Akka.Quartz.Actor #replace this
  - name: githubRepositoryName
    value: akkadotnet/Akka.Quartz.Actor #replace this

steps:
- task: UseDotNet@2
  displayName: 'Use .NET 6'
  inputs:
    version: '6.x'
- task: UseDotNet@2
  displayName: 'Use .NET Core 3.1'
  inputs:
    version: 3.1.x
- task: BatchScript@1
  displayName: 'FAKE Build'
  inputs:
    filename: build.cmd
    arguments: 'nuget nugetpublishurl=https://api.nuget.org/v3/index.json nugetkey=$(nugetKey)'

- task: GitHubRelease@0
  displayName: 'GitHub release (create)'
  inputs:
    gitHubConnection: $(githubConnectionName)
    repositoryName: $(githubRepositoryName)
    title: '$(projectName) v$(Build.SourceBranchName)'
    releaseNotesFile: 'RELEASE_NOTES.md'
    assets: |
     bin\nuget\*.nupkg
